---
name: mx_core_example
description: Demonstrates how to use the mx_core plugin.
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^0.1.2"
  flutter_localizations:
    sdk: flutter
  annotation_route: "^0.0.2"
  bot_toast: "^3.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  mx_core:
    path: "../"
  json_serializable: "^3.2.2"
  build_runner: "^1.6.8"
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/jsons/
  - assets/jsons/chart_example/
version: 1.1.0+13
